Repository peterbaumert/netbox-device-view, pull requests merged in 2023-07, with the labels that each got.

#8 Patchpanels and small fixes
  MANIFEST.in
  README.md
  examples/24xLC-Patchpanel.css
  examples/C2960X-24TD-L.css
  examples/C2960X-48TD-L.css
  examples/C9200-48P.css
  examples/C9200L-48P-4X.css
  examples/C9300-24T.css
  examples/C9500-24Y4C.css
  netbox_device_view/__init__.py
  netbox_device_view/static/netbox_device_view/css/device_view.css
  netbox_device_view/templates/netbox_device_view/deviceview.html
  netbox_device_view/utils.py
  netbox_device_view/views.py
Labels: feature

#13 Update views.py
  netbox_device_view/views.py
Labels: bug

#15 some fixes and height stuff
  examples/C2960X-24TD-L.css
  examples/C2960X-48TD-L.css
  examples/C8300-2N2S-4T2X.css
  netbox_device_view/template_content.py
  netbox_device_view/templates/netbox_device_view/deviceview.html
  netbox_device_view/templates/netbox_device_view/ports.html
  netbox_device_view/utils.py
  netbox_device_view/views.py
Labels: enhancement
